/* Generated By:JJTree: Do not edit this line. ASTreturnStatmentDef.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTreturnStatmentDef extends SimpleNode {
  public ASTreturnStatmentDef(int id) {
    super(id);
  }

  public ASTreturnStatmentDef(CLang p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CLangVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5438f218a3bc56b18140236b5745f3a6 (do not edit this line) */
