/* Generated By:JavaCC: Do not edit this line. CLangTreeConstants.java Version 7.0.5 */
public interface CLangTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSOURCECODEDEF = 1;
  public int JJTPARAMLISTDEF = 2;
  public int JJTPARAMDEF = 3;
  public int JJTFUNCTIONDEF = 4;
  public int JJTVARASSIGNDEFININIT = 5;
  public int JJTVARASSIGNDEF = 6;
  public int JJTVARDEFINEDEF = 7;
  public int JJTSTATEMENTBLOCKDEF = 8;
  public int JJTSTATEMENTDEF = 9;
  public int JJTIFSTATEMENTDEF = 10;
  public int JJTEXPRESSIONDEF = 11;
  public int JJTASSIGNEXPRESSIONDEF = 12;
  public int JJTBOOLEXPRESSIONDEF = 13;
  public int JJTBINARYBOOLEXPRESSIONORDEF = 14;
  public int JJTBINARYBOOLEXPRESSIONANDDEF = 15;
  public int JJTBINARYEXPRESSIONEQDEF = 16;
  public int JJTBINARYBOOLOPERATORCOMPAREDEF = 17;
  public int JJTBINARYBOOLEXPRESSIONCOMPAREDEF = 18;
  public int JJTADDEXPRESSIONDEF = 19;
  public int JJTMULEXPRESSIONDEF = 20;
  public int JJTUNARYEXPRESSIONDEF = 21;
  public int JJTCONSTEXPRESSIONDEF = 22;


  public String[] jjtNodeName = {
    "Start",
    "sourceCodeDef",
    "paramListDef",
    "paramDef",
    "functionDef",
    "varAssignDefInInit",
    "varAssignDef",
    "varDefineDef",
    "StatementBlockDef",
    "StatementDef",
    "IfStatementDef",
    "expressionDef",
    "assignExpressionDef",
    "boolExpressionDef",
    "binaryBoolExpressionOrDef",
    "binaryBoolExpressionAndDef",
    "binaryExpressionEqDef",
    "binaryBoolOperatorCompareDef",
    "binaryBoolExpressionCompareDef",
    "addExpressionDef",
    "mulExpressionDef",
    "unaryExpressionDef",
    "constExpressionDef",
  };
}
/* JavaCC - OriginalChecksum=09b98a586e641ba0cc9eb11f40db03c2 (do not edit this line) */
